version: "3.9"
networks:
  customnetwork:
    ipam:
      driver: default

services:
  app-a1:
    build: ./apps/app_a/
    command: elixir --sname "app-a1" --cookie secret --no-halt -S mix run
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - START_SERVER=true
    networks:
      - customnetwork
  app-a2:
    build: ./apps/app_a/
    command: elixir --sname "app-a2" --cookie secret --no-halt -S mix run
    networks:
      - customnetwork
  app-a3:
    build: ./apps/app_a/
    command: elixir --sname "app-a3" --cookie secret --no-halt -S mix run
    networks:
      - customnetwork

  app-b1:
    build: ./apps/app_b/
    command: elixir --sname "app-b1" --cookie secret --no-halt -S mix run
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - START_SERVER=true
    networks:
      - customnetwork
  app-b2:
    build: ./apps/app_b/
    command: elixir --sname "app-b2" --cookie secret --no-halt -S mix run
    networks:
      - customnetwork
  app-b3:
    build: ./apps/app_b/
    command: elixir --sname "app-b3" --cookie secret --no-halt -S mix run
    networks:
      - customnetwork

  livebook:
    build: ../livebook/
    networks:
      - customnetwork
    environment:
      - LIVEBOOK_PASSWORD=securesecret
#      - LIVEBOOK_DEFAULT_RUNTIME=standalone
      - LIVEBOOK_NODE=livebook
      - LIVEBOOK_COOKIE=secret
    ports:
      - "8080:8080"
      - "8081:8081"

