apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-a
spec:
  serviceName: "beam-cluster"
  replicas: 3
  selector:
    matchLabels:
      cluster: beam
  template:
    metadata:
      labels:
        component: app-a
        cluster: beam
    spec:
      containers:
        - name: app-a
          image: app-a
          imagePullPolicy: Never
          ports:
            - containerPort: 4001
            - containerPort: 9000
          env:
            - name: LIBCLUSTER_STRATEGY
              value: "kubernetes"
            - name: PORT
              value: "4001"
            - name: START_SERVER
              value: "true"
            - name: ERLANG_COOKIE
              value: "secret"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: [ "elixir" ]
          args: [
            "--name",
            "cluster-app@$(POD_NAME).beam-cluster.default.svc.cluster.local",
            "--cookie","$(ERLANG_COOKIE)",
            "--erl",
            "-kernel inet_dist_listen_min 9000 inet_dist_listen_max 9000",
            "--no-halt",
            "-S","mix",
            "run"
          ]
