apiVersion: v1
kind: Service
metadata:
  name: livebook-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
#    - name: web-socket
#      port: 8081
#      targetPort: 8081
  selector:
    component: livebook
