apiVersion: apps/v1
kind: Deployment
metadata:
  name: livebook-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: livebook
  template:
    metadata:
      labels:
        component: livebook
        cluster: beam
    spec:
      containers:
        - name: locallivebook
          image: locallivebook
          imagePullPolicy: Never
#          image: livebook/livebook
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: LIVEBOOK_PASSWORD
              value: "securesecret"
            - name: LIVEBOOK_COOKIE
              value: "secret"
            - name: ERLANG_COOKIE
              value: "secret"
            - name: LIVEBOOK_DISTRIBUTION
              value: "name"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: LIVEBOOK_NODE
              value: "cluster-app@$(POD_IP)"
            - name: LIVEBOOK_DEFAULT_RUNTIME
              value: "attached:$(LIVEBOOK_NODE):$(LIVEBOOK_COOKIE)"
#          command: [ "elixir" ]
#          args: [
#            "--name",
#            "livebok@$(POD_IP)",
#            "--cookie","$(ERLANG_COOKIE)",
#            "--no-halt",
#            "-S","mix",
#            "run"
#          ]
