apiVersion: v1
kind: Pod
metadata:
  name: livebook
  labels:
    component: livebook
spec:
  containers:
    - name: livebook
      image: livebook
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
        - containerPort: 8081
      env:
        - name: LIBCLUSTER_STRATEGY
          value: "kubernetes"
        - name: LIVEBOOK_PASSWORD
          value: "securesecret"
        - name: LIVEBOOK_COOKIE
          value: "secret"
        - name: ERLANG_COOKIE
          value: "secret"
        - name: LIVEBOOK_DISTRIBUTION
          value: "name"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LIVEBOOK_NODE
          value: "cluster-app@$(POD_NAME)"
        - name: LIVEBOOK_DEFAULT_RUNTIME
          value: "attached:$(LIVEBOOK_NODE):$(LIVEBOOK_COOKIE)"
