apiVersion: v1
kind: Pod
metadata:
  name: livebook
  labels:
    component: livebook
spec:
  containers:
    - name: livebook
      image: livebook/livebook:edge
      ports:
        - containerPort: 8080
        - containerPort: 8081
      env:
        - name: LIVEBOOK_PASSWORD
          value: "securesecret"
        - name: LIVEBOOK_COOKIE
          value: "secret"
        - name: ERLANG_COOKIE
          value: "secret"
        - name: LIVEBOOK_DISTRIBUTION
          value: "name"
        - name: LIVEBOOK_PORT
          value: "8080"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LIVEBOOK_NODE
          value: "cluster-app@$(POD_NAME)"
        - name: LIVEBOOK_DEFAULT_RUNTIME
          value: "attached:$(LIVEBOOK_NODE):$(LIVEBOOK_COOKIE)"

---
apiVersion: v1
kind: Service
metadata:
  name: livebook
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  #    - name: web-socket
  #      port: 8081
  #      targetPort: 8081
  selector:
    component: livebook
