apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
spec:
  replicas: 3
  selector:
    matchLabels:
      component: app-b
  template:
    metadata:
      labels:
        component: app-b
        cluster: beam
    spec:
      containers:
        - name: app-b
          image: app-b
          imagePullPolicy: Never
          ports:
            - containerPort: 4002
            - containerPort: 9000
          env:
            - name: LIBCLUSTER_STRATEGY
              value: "gossip"
            - name: PORT
              value: "4002"
            - name: START_SERVER
              value: "true"
            - name: ERLANG_COOKIE
              value: "secret"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: [ "elixir" ]
          args: [
            "--name",
            "app-b@$(POD_IP)",
            "--cookie","$(ERLANG_COOKIE)",
            "--erl",
            "-kernel inet_dist_listen_min 9000 inet_dist_listen_max 9000",
            "--no-halt",
            "-S","mix",
            "run"
          ]

---
apiVersion: v1
kind: Service
metadata:
  name: app-b
spec:
  type: LoadBalancer
  ports:
    - port: 4002
      targetPort: 4002
  selector:
    component: app-b

